In [5]:
import csv
import pathlib
import pandas as pd

In [6]:
# Read in clean Regular data
Regular_clean = pathlib.Path('../data/Regular_clean_v1.csv')
Regular_clean_df = pd.read_csv(Regular_clean, index_col=False)

In [3]:
# Read in raw Airbnb data
airbnb_raw = pathlib.Path('../data/Airbnb_raw.csv')
airbnb_raw_df = pd.read_csv(airbnb_raw, index_col=False)

In [4]:
# Drop unused columns
airbnb_clean_df = airbnb_raw_df.drop(['Index',
                   'status',
                   'nightPriceÙ€native',
                   'weeklyPrice',
                   'monthlyPrice',
                   'cleaningFeeNative',
                   'image',
                   'rentalIncome',
                   'state',
                   'roomType',
                   'roomTypeCategory',
                   'amenities',
                   'reviews',
                   'createdAt',
                   'updatedAt',
                   'url',
                   'rental_income',
                   'neighborhood',
                   'nightRate',
                   'airbnbZIP'
                   
                  ],axis=1)

In [5]:
# rename and reorder columns
airbnb_clean_df['Title'] = ''
airbnb_clean_df['Price'] = ''
airbnb_clean_df['clean_mthly_price'] = ''
airbnb_clean_reorder_df= airbnb_clean_df[['id',
                                  'propertyId',
                                  'source',
                                  'airbnbNeighborhoodId',
                                  'name',
                                  'Title',
                                  'nightPrice',
                                  'numOfBaths',
                                  'numOfBeds',
                                  'Price',
                                  'address',
                                  'airbnbNeighborhood', 
                                  'airbnbCity',
                                  'zip',
                                  'propertyType',
                                  'lat',
                                  'lon',
                                  'capacityOfPeople',
                                  'numOfRooms',
                                  'reviewsCount',
                                  'startRating',
                                  'occupancy',
                                  'nightsBooked',
                                  'clean_mthly_price']]
airbnb_clean_reorder_df.head()

,id,propertyId,source,airbnbNeighborhoodId,name,Title,nightPrice,numOfBaths,numOfBeds,Price,...,propertyType,lat,lon,capacityOfPeople,numOfRooms,reviewsCount,startRating,occupancy,nightsBooked,clean_mthly_price
0,28612684,11695191,Airbnb,7877,Beautiful private studio by LAX and the ocean,,124,1.0,2.0,,...,Apartment,33.959801,-118.405807,2,0.0,87,5.0,89,326,
1,28612665,15915760,Airbnb,7877,"Beautiful & Private Home with Big Backyard, BB...",,268,3.0,4.0,,...,House,33.964260,-118.398590,8,3.0,37,5.0,92,337,
2,28612651,1650397,Airbnb,7877,LAXclose-modern&green guest Suite,,115,0.5,4.0,,...,Guest suite,33.960190,-118.392761,6,1.0,437,5.0,68,248,
3,28612691,16824550,Airbnb,7877,Studio in Westchester. Near LAX.,,93,1.0,2.0,,...,Apartment,33.960659,-118.388420,3,0.0,302,5.0,99,364,
4,28612677,17097814,Airbnb,7877,Private/Quiet Westside Residential House,,90,1.0,2.0,,...,House,33.962341,-118.386002,4,1.0,139,5.0,97,355,

In [6]:
# rename columns so both Regular and Airbnb data are aligned
airbnb_clean_reorder_df.rename({'airbnbNeighborhoodId': 'neighborhood_id',
                                     'name': 'description',
                                     'airbnbCity': 'city',
                                     'airbnbNeighborhood': 'neighborhood'},axis = 1, inplace = True)

C:\Users\jmiln\Anaconda3\lib\site-packages\pandas\core\frame.py:4438: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [7]:
airbnb_clean_reorder_df.head()

,id,propertyId,source,neighborhood_id,description,Title,nightPrice,numOfBaths,numOfBeds,Price,...,propertyType,lat,lon,capacityOfPeople,numOfRooms,reviewsCount,startRating,occupancy,nightsBooked,clean_mthly_price
0,28612684,11695191,Airbnb,7877,Beautiful private studio by LAX and the ocean,,124,1.0,2.0,,...,Apartment,33.959801,-118.405807,2,0.0,87,5.0,89,326,
1,28612665,15915760,Airbnb,7877,"Beautiful & Private Home with Big Backyard, BB...",,268,3.0,4.0,,...,House,33.964260,-118.398590,8,3.0,37,5.0,92,337,
2,28612651,1650397,Airbnb,7877,LAXclose-modern&green guest Suite,,115,0.5,4.0,,...,Guest suite,33.960190,-118.392761,6,1.0,437,5.0,68,248,
3,28612691,16824550,Airbnb,7877,Studio in Westchester. Near LAX.,,93,1.0,2.0,,...,Apartment,33.960659,-118.388420,3,0.0,302,5.0,99,364,
4,28612677,17097814,Airbnb,7877,Private/Quiet Westside Residential House,,90,1.0,2.0,,...,House,33.962341,-118.386002,4,1.0,139,5.0,97,355,

In [10]:
# merge the two datasets together
air_reg_merged_df = pd.concat([airbnb_clean_reorder_df, Regular_clean_df])

In [11]:
# export combined datasets to a csv
air_reg_merged_df.to_csv('../data/combined_clean_v1.csv',index = False)