In [1]:
import requests
from config import api_key

In [2]:
import pandas as pd

In [3]:
headers = {
    'x-api-key': api_key
}

## Get Los Angeles Neighborhoods

In [4]:
state = 'CA'
city = 'Los%20Angeles'

In [5]:
url =  f'https://api.mashvisor.com/v1.1/client/city/neighborhoods/{state}/{city}'

In [7]:
response = requests.get(url, headers=headers)

In [15]:
results_list = response.json()['content']['results']
results_list

In [30]:
los_angeles_neighborhoods_df = pd.DataFrame(results_list)
los_angeles_neighborhoods_df

,id,city,latitude,longitude,name,state,county,is_village
0,7877,Los Angeles,33.952138,-118.404407,Westchester,CA,Los Angeles,0
1,13017,Los Angeles,34.238792,-118.477272,North Hills,CA,Los Angeles,0
2,13176,Los Angeles,34.228894,-118.444025,Panorama City,CA,Los Angeles,0
3,13327,Los Angeles,33.974969,-118.420888,Playa Vista,CA,Los Angeles,0
4,19810,Los Angeles,34.078243,-118.546495,Pacific Palisades,CA,Los Angeles,0
...,...,...,...,...,...,...,...,...
91,403192,Los Angeles,34.046386,-118.296546,Harvard Heights,CA,Los Angeles,0
92,403193,Los Angeles,34.043706,-118.317168,Arlington Heights,CA,Los Angeles,0
93,403194,Los Angeles,34.055494,-118.369992,South Carthay,CA,Los Angeles,0
94,403195,Los Angeles,34.038472,-118.380274,Crestview,CA,Los Angeles,0
95,417433,Los Angeles,34.105276,-118.184570,Hermon,CA,Los Angeles,0

## Get Airbnb Info for Neighborhoods

In [31]:
all_neighborhoods_list = []

In [32]:
#neighborhood_id = 7877
for neighborhood_id in los_angeles_neighborhoods_df['id']:
    airbnb_url = f'https://api.mashvisor.com/v1.1/client/neighborhood/{neighborhood_id}/airbnb/details'
    params = {
        'state': 'CA',  # required per API documentation
        'items': 20     # appears to max at 20
    }
    try:
        response = requests.get(airbnb_url, params=params, headers=headers)
    except Exception as e:
        f"Failed to get response: {e}"

    try:
        properties = response.json()['content']['properties']
    except Exception as e:
        f"Failed to extract properties from response: {e}"
    else:
        all_neighborhoods_list = all_neighborhoods_list + properties

In [34]:
all_neighborhoods_df = pd.DataFrame(all_neighborhoods_list)
all_neighborhoods_df

,id,propertyId,source,status,nightPriceÙ€native,nightPrice,weeklyPrice,monthlyPrice,cleaningFeeNative,numOfBaths,...,numOfBeds,lat,lon,image,url,rental_income,neighborhood,nightRate,property_id,airbnbZIP
0,28612684,11695191,Airbnb,ACTIVE,125,124,0,0,60.0,1.0,...,2.0,33.959801,-118.405807,https://a0.muscache.com/im/pictures/06e8fa01-9...,None,3310.8,"{'id': 7877, 'name': 'Westchester/Playa Del Rey'}",124,11695191,90045
1,28612665,15915760,Airbnb,ACTIVE,259,268,0,0,119.0,3.0,...,4.0,33.964260,-118.398590,https://a0.muscache.com/im/pictures/1b7b248a-8...,None,7396.8,"{'id': 7877, 'name': 'Westchester/Playa Del Rey'}",268,15915760,90045
2,28612651,1650397,Airbnb,ACTIVE,115,115,750,2900,40.0,0.5,...,4.0,33.960190,-118.392761,https://a0.muscache.com/im/pictures/27330186/9...,None,2346.0,"{'id': 7877, 'name': 'Westchester/Playa Del Rey'}",115,1650397,90045
3,28612691,16824550,Airbnb,ACTIVE,98,93,0,0,15.0,1.0,...,2.0,33.960659,-118.388420,https://a0.muscache.com/im/pictures/aaa24031-c...,None,2762.1,"{'id': 7877, 'name': 'Westchester/Playa Del Rey'}",93,16824550,90045
4,28612677,17097814,Airbnb,ACTIVE,98,90,0,0,75.0,1.0,...,2.0,33.962341,-118.386002,https://a0.muscache.com/im/pictures/1b15f579-a...,None,2619.0,"{'id': 7877, 'name': 'Westchester/Playa Del Rey'}",90,17097814,90045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1509,28617277,17349615,Airbnb,ACTIVE,95,85,0,0,30.0,1.0,...,1.0,34.104301,-118.178337,https://a0.muscache.com/im/pictures/68c7e1b8-9...,None,2448.0,"{'id': 417433, 'name': 'Hermon'}",85,17349615,90042
1510,28617298,21445303,Airbnb,ACTIVE,125,91,0,0,NaN,1.0,...,1.0,34.108189,-118.178627,https://a0.muscache.com/im/pictures/6f9511f3-3...,None,1992.9,"{'id': 417433, 'name': 'Hermon'}",91,21445303,90042
1511,28617290,3442441,Airbnb,ACTIVE,85,85,550,1950,40.0,1.5,...,1.0,34.108582,-118.180702,https://a0.muscache.com/im/pictures/e69d01d0-6...,None,2040.0,"{'id': 417433, 'name': 'Hermon'}",85,3442441,90042
1512,28617305,46566192,Airbnb,ACTIVE,60,76,0,0,70.0,1.0,...,1.0,34.105530,-118.188873,https://a0.muscache.com/im/pictures/faaada0a-c...,None,1390.8,"{'id': 417433, 'name': 'Hermon'}",76,46566192,90042
1513,28617284,9653615,Airbnb,out of market range,95,126,0,0,75.0,1.0,...,1.0,34.107609,-118.178299,https://a0.muscache.com/im/pictures/c3e3c823-5...,None,3288.6,"{'id': 417433, 'name': 'Hermon'}",126,9653615,90042

In [35]:
all_neighborhoods_df.to_csv('../all_neighborhoods.csv')